### ISSUE TITLE
Live Reload is disconnecting wss://

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/hotwire-livereload#14]
I have a simple template that renders, based on the hotwire rails sample App. Some components are hooked up to Stimulus controllers and call the back-end. The back-end responds, does some work, and returns a status like head :ok. 

Once I do that, the console starts logging connection errors to wss://

Why does ActionCable all of a sudden become disconnected and all uppity, filling the console with these errors? Am I somehow causing this disconnect? Is there some special thing we are supposed to do to silence that? I am not using ActionCable as far as I know... but maybe with all the turbo related code in this Rails 7 hotwire App I am. Anyway, I am looking for tips on what to look for to try and mitigate a console filling with these messages. 

    Firefox can’t establish a connection to the server at wss://webapp.test/cable. [hotwire-livereload.source.js:226](https://webapp.test/assets/hotwire-livereload.source.js)

    The connection to wss://webapp.test/cable was interrupted while the page was loading.

**Comment by kirillplatonov** [comment]
@resistorsoftware do you have an issue with disconnected WebSockets only in Firefox?

**Comment by resistorsoftware** [comment]
I think this issue is related to errors in the Rails code during execution, and probably not related to the browser Firefox or with Hotwire-livereload. I am getting used to the way things happen now. So I think, but I am not 100% since I have not been developing for awhile, that if I make an error in Rails, the console fills with these kinds of broken WSS errors. Upon a refresh and bug fix, the console is fine. 

If I ever come across this again and it is repeatable and demonstrable, I will file a proper issue with code to demo the issue.
