### ISSUE TITLE
Hotwire Problems I cannot Figure Out

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/hotwire-livereload#15]
I edit a view. So I change a Polaris view component maybe. Whatever. 

The system watchers issue a Build. Things build! But the browser reload process shows wss cut off, and other than those messages contantly building, the template no longer auto-refreshes. So I am curious. How did I manage to somehow misconfigure my Hotwire Reload from reloading ERB views when they change. The message from Action Cable under the Build message in the logs is, Template "blah.html.erb" changed, reload => false... 

Usually this Hotwire Reload thing works great. But somehow I managed to get it screwed up. Any clues as to where there might be a config for this I can tinker with? My development use of it looks like this... 

    <%= stylesheet_link_tag "application", 'polaris_view_components', "data-turbo-track": "reload"  %>
    <%= javascript_include_tag 'application' %>
    <% if Rails.env.development? %>
      <%= javascript_include_tag 'hotwire-livereload', defer: true %>
    <% end %>

**Comment by lcuevastodoit** [comment]
@kirillplatonov hope you have any chance to see this issue, I saw the same behavior ERB files change, no reload occurs.
