### ISSUE TITLE
Problems with reloading

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/hotwire-livereload#16]
My logs show when ERB files change, no reload occurs. This is so strange! Also, my browser shows lots of problems with wss:// connections. I am really trying hard to figure out where the true issue lies! So far, no clues...
```
Rebuilding...
Done in 18ms.
[ActionCable] Broadcasting to hotwire-reload: {:changed=>["/Users/beers/Documents/Workspace/Apps/planty/app/views/kilts/index.html.erb"], :force_reload=>false}
[watch] build started (change: "app/javascript/application.js")
[watch] build finished
Rebuilding...
Done in 19ms.
[ActionCable] Broadcasting to hotwire-reload: {:changed=>["/Users/beers/Documents/Workspace/Apps/planty/app/javascript/application.js"], :force_reload=>true}

Example of browser messages.


    Firefox can’t establish a connection to the server at wss://myshite.test/cable. hotwire-livereload-69f109e9f29dd4f334a14c739a16f66d96595dcede55037f287ea8712288c0ae.js:226:31
    The connection to wss://myshite.test/cable was interrupted while the page was loading. hotwire-livereload-69f109e9f29dd4f334a14c739a16f66d96595dcede55037f287ea8712288c0ae.js:226:31
    Firefox can’t establish a connection to the server at wss://myshite.test/cable. hotwire-livereload-69f109e9f29dd4f334a14c739a16f66d96595dcede55037f287ea8712288c0ae.js:226:31
    The connection to wss://myshite.test/cable was interrupted while the page was loading. hotwire-livereload-69f109e9f29dd4f334a14c739a16f66d96595dcede55037f287ea8712288c0ae.js:226:31
    Firefox can’t establish a connection to the server at wss://myshite.test/cable. hotwire-livereload-69f109e9f29dd4f334a14c739a16f66d96595dcede55037f287ea8712288c0ae.js:226:31
    The connection to wss://myshite.test/cable was interrupted while the page was loading. hotwire-livereload-69f109e9f29dd4f334a14c739a16f66d96595dcede55037f287ea8712288c0ae.js:226:31

**Comment by lcuevastodoit** [comment]
@kirillplatonov hope you have any chance to see this issue, I saw the same behavior ERB files change, no reload occurs.

**Comment by kirillplatonov** [comment]
@lcuevastodoit do you also use Firefox? Could you please provide examples of errors you get in the browser?

**Comment by lcuevastodoit** [comment]
I will getting the screen captures in a minutes but you can see rigth now in this Replit https://replit.com/@lcuevastodoit/test-hotwire-live-reloading

**Comment by kirillplatonov** [comment]
> I will getting the screen captures in a minutes but you can see rigth now in this Replit https://replit.com/join/cumjsjoifb-lcuevastodoit

Could you please share it via public Github gist/repo? I don't have Replit account.

**Comment by lcuevastodoit** [comment]
I just made this video gif
![live-reloading](https://user-images.githubusercontent.com/25910807/169678054-08eea764-c196-4cfa-bd94-02d810c7ac3a.gif)

**Comment by lcuevastodoit** [comment]
you can fork the code in https://replit.com/@lcuevastodoit/test-hotwire-live-reloading

**Comment by lcuevastodoit** [comment]
also you can browse the code (no need to Login)
![image](https://user-images.githubusercontent.com/25910807/169678290-fb71d39d-57da-4ed4-baea-fb369691b578.png)

**Comment by lcuevastodoit** [comment]
Maybe this help,  when hotwire reloading is working good, it shows one Action Cable Broadcasting log and after that one Hotwire::Livereload::ReloadChannel transmitting log:
![image](https://user-images.githubusercontent.com/25910807/169718429-e6fcf8ef-742f-4ae6-9210-93f1ae37be9b.png)

And when is not working only send the Action Cable Broadcasting
![image](https://user-images.githubusercontent.com/25910807/169718468-8bfae870-ea0e-4931-875c-a83279ce3876.png)

**Comment by kirillplatonov** [comment]
@lcuevastodoit it seems like there was a bug in older puma that caused issues with Action Cable broadcasting. Upgrading puma to the latest version helps to resolve this: `bundle update puma`

**Comment by lcuevastodoit** [comment]
Excelent @kirillplatonov you are the master, the problem was puma 5.6.0
Solved with puma 5.6.4
```
bundle update puma
Installing puma 5.6.4 (was 5.6.0) with native extensions
Removing puma (5.6.0)
Bundle updated!
~/test-hotwire-live-reloading$ bundle info puma
  * puma (5.6.4)
  
```

**Comment by resistorsoftware** [comment]
I am running Puma 5.6.4, yet when I change an ERB file, I see this in my console, and the hotwire-reload has not reloaded the page? 

 Rebuilding...
10:33:29 css.1  | Done in 14ms.
10:33:29 web.1  | [ActionCable] Broadcasting to hotwire-reload: {:changed=>["/Users/Documents/Workspace/Apps/2022/rancid_butter/app/views/transmissions/index.html.erb"], :force_reload=>false}

**Comment by kirillplatonov** [comment]
@resistorsoftware please provide a sample app with the reproducible issue. Without this, it's impossible to investigate what went wrong.

**Comment by resistorsoftware** [comment]
Impossible! I will just soldier on. Thanks!

**Comment by tsaghir** [comment]
Hi @resistorsoftware, have you maybe resolved your issue?
