### ISSUE TITLE
This Gem requires Redis implicitly

### ISSUE THREAD

**Issue by zfz** [kirillplatonov/hotwire-livereload#20]
Hi, I didn't know this Gem will replace `Async` with `Redis` in the Action Cable Dev environment. Spent some time figuring out what happened when starting my dev env. 

Just curious is it possible to stick to `Async`? Or at least we should mention that Redis is a prerequisite in the README.

Thanks!

**Comment by kirillplatonov** [comment]
Hi @zfz,

Unfortunately, broadcasting to the browser won't work with `Async` so we have to stick with `Redis`. I added it to Dependencies section in README: https://github.com/kirillplatonov/hotwire-livereload#dependencies
