### ISSUE TITLE
Add configurable delay before reload

### ISSUE THREAD

**Issue by alec-c4** [kirillplatonov/hotwire-livereload#23]
Sometimes assets builder is not so fast as your gem :)

**Comment by kirillplatonov** [comment]
PR would be welcome for this feature 🙂
Do you have issues with webpack or another asset builder?

**Comment by alec-c4** [comment]
I use esbuild :)

**Comment by elik-ru** [comment]
@alec-c4 Probably you should remove source files from watched dirs and watch only on build files.

**Comment by LEstradioto** [comment]
@elik-ru nice !

I was using esbuild and tailwind and having delay problems, solved by deleting `app/assets/stylesheets` and adding `app/assets/builds` to `listen_paths`, in my case:

```ruby
# development.rb

  config.hotwire_livereload.disable_default_listeners = true
  config.hotwire_livereload.listen_paths = [
    Rails.root.join("app/views"),
    Rails.root.join("app/helpers"),
    Rails.root.join("app/javascript"),
    Rails.root.join("app/assets/images"),
    Rails.root.join("config/locales"),
    Rails.root.join("app/assets/builds")
  ]
```

**Comment by elik-ru** [comment]
@LEstradioto I have made a PR with many improvements: https://github.com/kirillplatonov/hotwire-livereload/pull/34
I would appreciate if you can give it a try and leave some feedback.

**Comment by kirillplatonov** [comment]
Added support for `jsbundling-rails` and `cssbundling-rails` output folder out of the box: https://github.com/kirillplatonov/hotwire-livereload/pull/37
