### ISSUE TITLE
More detailed installation instructions?

### ISSUE THREAD

**Issue by marckohlbrugge** [kirillplatonov/hotwire-livereload#28]
Love the idea of this gem! ❤️

I followed the README and my browser console says `[Hotwire::Livereload] Websocket connected`. But when I change any file, nothing gets reloaded.

Whatever it is, it's probably user error. But I followed the README and don't see anything in the Rails logs or browser console.

Any additional installation instructions (perhaps related to ActionCable) would be appreciated 🙌

**Comment by marckohlbrugge** [comment]
Some additional info:

Redis shows `1661027312.812270 [1 [::1]:54908] "subscribe" "hotwire-reload"` on page load so it seems like ActionCable is correctly connected to Redis. Changing any files does not trigger any other Redis events.

**Comment by kirillplatonov** [comment]
Hey Marc,

It sounds like ActionCable and Redis are correctly connected and there are some issues with detecting file changes. When file changed you should see the following messages in Rails logs:
```bash
[ActionCable] Broadcasting to hotwire-reload: {:changed=>["/Users/kirill/Code/demo-app/app/views/posts/index.html.erb"], :force_reload=>false}
Hotwire::Livereload::ReloadChannel transmitting {"changed"=>["/Users/kirill/Code/demo-app/app/views/posts/index.html.erb"], "force_reload"=>false} (via streamed from hotwire-reload)
```

1. What is the path for the file you trying to change?
2. Could you please share a custom configuration for Hotwire Livereload (if any)?
3. Just in case, make sure there's no file `tmp/livereload-disabled.txt` cause it's blocking livereload.

**Comment by marckohlbrugge** [comment]
I've narrowed it down to `Rails::Server` not being defined for my app. I use overmind with puma and `rails server` doesn't seem to run. I never noticed it before, as I don't use it.

Either way, it seems like the issue might be due to my specific installation rather than the gem.

**Comment by marckohlbrugge** [comment]
@kirillplatonov The new version works for me now. Thank you for the fix! 💖

**Comment by kirillplatonov** [comment]
Glad it's working now ✌️
