### ISSUE TITLE
Puma 6.0.0 issue

### ISSUE THREAD

**Issue by Pash-tet** [kirillplatonov/hotwire-livereload#30]
I created a new application with puma 6.0.0 and saw that the gem does not work with this puma version. I can't figure out if this is a problem with livereload or puma )

**Comment by kirillplatonov** [comment]
It looks like it just has been released :) I will check compatibility.
Do you run the puma process directly or via `rails server` command?

**Comment by Pash-tet** [comment]
> It looks like it just has been released :) I will check compatibility. Do you run the puma process directly or via `rails server` command?

yes, i run puma process throught rails s

**Comment by olivrg** [comment]
Not sure if this is related but I've noticed that this gem has stopped working as well. It worked fine on a previous project 10 days ago. Today I'm getting this error when I save an ERB file: 
`[ActionCable] Broadcasting to hotwire-reload: {:changed=>["/Users/username/Desktop/Workspace/projectx/app/views/home/index.html.erb"], :force_reload=>false}`

`force reload =>false` I'm not sure what's changed but I'm on the same Rails version and running `Puma version: 5.6.5 (ruby 3.1.2-p20) ("Birdie's Version")`

**Comment by solilin** [comment]
The same problem I have with Puma 6.0.0. With gem 'puma', '5.6.4' everything works fine.

**Comment by kirillplatonov** [comment]
The issue is caused by this bug: https://github.com/puma/puma/issues/2999

It's worth waiting with Puma 6 upgrade until the patch with fixes is released.

**Comment by edulima** [comment]
Just added this gem to my project but getting this error `Uncaught ReferenceError: Turbo is not defined`. My project uses turbolink instead of Turbo. I guess this is where the error is coming from. Am I correct to assume the gem doesn't have support for turbolinks?

**Comment by kirillplatonov** [comment]
@edulima yes, this gem supports only `Turbo`. `Turbolinks` is no longer maintained.

**Comment by edulima** [comment]
Thanks @kirillplatonov. Great work on this gem.

**Comment by kirillplatonov** [comment]
Puma v6.0.1 with bugfixes has been released: https://github.com/puma/puma/releases/tag/v6.0.1
It should be safe to upgrade now.
