### ISSUE TITLE
Using Webpack

### ISSUE THREAD

**Issue by saint-james-fr** [kirillplatonov/hotwire-livereload#32]
Hey nice gem, thanks!
I've tried it on bare configuration and it's great but using Webpack and for example SASS + Bootstrap configuration, It does not work and force_reload the page, is there any turnaround? I'd be glad to know more about the possible issue. thanks!

**Comment by kirillplatonov** [comment]
Hey,
Which files do you edit when the gem force reloads the page?
And could you please run this command in your project's root and copy the output:
```bash
rails runner "puts Rails.application.config.hotwire_livereload"
```

**Comment by kirillplatonov** [comment]
If you're using webpack & sass with `jsbundling-rails` or `cssbundling-rails` then they should work out of the box without additional configuration now: https://github.com/kirillplatonov/hotwire-livereload/pull/37
