### ISSUE TITLE
undefined local variable or method `hotwire_livereload_tags' 

### ISSUE THREAD

**Issue by pmpinto** [kirillplatonov/hotwire-livereload#38]
So I followed your tutorial here: https://kirillplatonov.com/posts/hotwire-livereload/

Added the gem to my Gemfile, ran `bundle install` and then ran `rails livereload:install`.
But then when I restart the local server (through `docker-compose`) it doesn't seem to be able to find `hotwire_livereload_tags`.

Ruby 3.2.1
Rails 7.0.4.3
Puma 5.6.5

Anything I might have missed?

**Comment by pmpinto** [comment]
Here's something else:
If I add `gem 'hotwire-livereload'` under `group :development do`, it doesn't seem to be doing anything.
But if I add it outside of any `group`, and then save a file, it attempts to do something, but fails:

```
| Redis::CannotConnectError: Error connecting to Redis on localhost:6379 (Errno::EADDRNOTAVAIL)
| --- Caused by: ---
| Errno::EADDRNOTAVAIL: Cannot assign requested address - connect(2) for [::1]:6379
```

Turns out I didn't have a Redis server running. So I installed Redis through `brew install redis` and then started a server with `redis-server`.
It spins a server listening at port `6379` as expected.

But live reload still doesn't work. The exact same error is returned when a file is saved. I have a feeling this has something to do with Docker, but I have no idea how to fix it.

**Comment by pmpinto** [comment]
Here's more:
I added the following to my `docker-compose.yml` file:
```yml
services:
# …
  cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
volumes:
  cache:
```

This seems to spawn not only my rails app server, but also the redis server inside the same container.

Then I changed `development.url` in `config/cable.yml` to be `redis://cache:6379/1` instead of `redis://localhost:6379/1`.

All this got rid of the errors from above. But it still doesn't actually work. It now outputs the following:
```
| [ActionCable] Broadcasting to hotwire-reload: {:changed=>["/rails/app/assets/stylesheets/includes/_footer.scss"], :force_reload=>false}
| [ActionCable] Broadcasting to hotwire-reload: {:changed=>["/rails/app/views/users/login.html.erb"], :force_reload=>false}
```

So I saved `_footer.scss` and `login.html.erb` — adding changes to both files, not just saving them — and nothing actually happened.

**Comment by pmpinto** [comment]
Even with the following in `config/environments/development.rb`:
```ruby
config.hotwire_livereload.force_reload_paths << Rails.root.join('app/assets/stylesheets')
config.hotwire_livereload.force_reload_paths << Rails.root.join('app/javascript')
```

It outputs this:
```
| [ActionCable] Broadcasting to hotwire-reload: {:changed=>["/rails/app/assets/stylesheets/includes/_footer.scss"], :force_reload=>true}
| [ActionCable] Broadcasting to hotwire-reload: {:changed=>["/rails/app/views/users/login.html.erb"], :force_reload=>false}
```

Notice the `:force_reload` is `true` for the SCSS file, but still nothing happens.

**Comment by pmpinto** [comment]
🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 

Guess who forgot to uncomment the `hotwire_livereload_tags` back from when the server wouldn't run with it? ☝️😅 

Whoever is reading this, make sure you have these in your `application.html.erb`, and they're _not_ commented out.
```erb
    <%= action_cable_meta_tag %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
```

All good now ✅

**Comment by kirillplatonov** [comment]
Glad to hear you figured this out! 🙌

**Comment by pmpinto** [comment]
One thing still is true though. I can't place the `gem` inside the `development` group:
```ruby
group :development do
  gem 'hotwire-livereload'
end
```

Any issues of running it also in production?
