### ISSUE TITLE
Is turbo-rails also a dependency to hotwire-livereload? Dealing with app updated to Rails 7.

### ISSUE THREAD

**Issue by ChidoYo** [kirillplatonov/hotwire-livereload#41]
I just installed this on an rails app that I just updated from rails 5 to rails 7.0.2.
I installed hotwire-livereload to my app following your steps.
When I tried to make a small update to an html.erb file I got the error:
`Uncaught ReferenceError: Turbo is not defined`
Does this mean I have to install `turbo rails` as well?

**Comment by kirillplatonov** [comment]
This gem is designed for apps that are using Hotwire Turbo. You'll either need `turbo-rails` gem or `@hotwired/turbo` via npm installed and configured in your app.
