### ISSUE TITLE
issues with running javascript

### ISSUE THREAD

**Issue by jay754** [kirillplatonov/hotwire-livereload#44]
I have installed the gem and html and css are hot reloading, but for some reason javascript isn't being updated.

Any idea?

**Comment by kirillplatonov** [comment]
In which folders your js located? Do you use `jsbundling-rails`?

**Comment by jay754** [comment]
the js is in app/javascript.

config.hotwire_livereload.force_reload_paths << Rails.root.join("app/javascript") app/javascript

is in the development.rb
