### ISSUE TITLE
after proper installation its show :- undefined local variable or method `hotwire_livereload_tags' for #<ActionView::Base:0x000000000e3878>

### ISSUE THREAD

**Issue by princetechs** [kirillplatonov/hotwire-livereload#48]
os:- mac-m1-16-sonama
rails. :- 7

after install ,, when go to reload its railse a error :- undefined local variable or method `hotwire_livereload_tags' for 
![Uploading github_live_reload_issue.png…]()

**Comment by kirillplatonov** [comment]
Could not reproduce on newly generated Rails 7 app. Make sure to follow steps in Getting started guide: https://github.com/kirillplatonov/hotwire-livereload?tab=readme-ov-file#getting-started
And if the error still occurs please provide reproduction steps so I could investigate the issue.
