### ISSUE TITLE
Preserve scroll position issue with lazy loaded content and link targeting a frame

### ISSUE THREAD

**Issue by adrienpoly** [kirillplatonov/hotwire-livereload#50]
From 1.3 I noticed what I think is a bug with the way the scroll is preserved.

## Lazy loaded content
I have a view with lazy loaded content. (infinite scroll). While I am scrolling down new content will appear but now as the new content appear I am being scrolled UP creating a strange effect.

## Links targeting a frame

another case is when I have a link that targets a Turbo Frame. By example a link that will show some content in a text zone. Then same thing the preserve scroll will kick in and break the usual UX.

**Comment by jwilsjustin** [comment]
Looks like this may have been fixed with #47. It's merged into main, but hasn't been released yet 👍

**Comment by kirillplatonov** [comment]
Published v1.3.1 with the fix from #47. @adrienpoly please let me know if it solves the issue for you.

**Comment by jwilsjustin** [comment]
I quick look at our implementation and the 1.3.1 release looks great! Thanks @kirillplatonov!

**Comment by kirillplatonov** [comment]
Awesome! 🎉

**Comment by adrienpoly** [comment]
I confirm that this fixed my issues thanks
