### ISSUE TITLE
CSS Not Reloading

### ISSUE THREAD

**Issue by jameskerr** [kirillplatonov/hotwire-livereload#51]
Hello, happy new year, and thank you for your time and effort creating this package.

I have a Rails 7.1 app with a default setup, I've added the gem, installed redis, and run your installer. HTML seems to reload, but I'm not able to have my styles auto reload. Here's a video. Is there anything I'm doing wrong that stands out?

https://github.com/kirillplatonov/hotwire-livereload/assets/3460638/7dc93a81-7918-410a-aee6-a25769f34620

**Comment by kirillplatonov** [comment]
Hi @jameskerr,

If this still relevant, could you please send output of gem config:
```bash
bin/rails runner "puts Rails.application.config.hotwire_livereload"
```

Also, please check `data-turbo-track="reload"` attribute on your CSS files. If not then you need to configure force reloading for CSS: https://github.com/kirillplatonov/hotwire-livereload?tab=readme-ov-file#force-reload

**Comment by jameskerr** [comment]
Thanks for your response. I'm now using postcss to bundle and all is working as intended. I run the app with bin/dev and everything works.

When I created this issue, I was using vanilla CSS. I'll close it since I can't reproduce anymore.

Since most people use cssbundling and jsbundling (im guessing) I think the default rails assets setup doesn't get as much love as it could. 

Thanks for this library. I can't believe Rails doesn't ship live reloading by default. That needs to change.
