### ISSUE TITLE
Reloads on error pages

### ISSUE THREAD

**Issue by holman** [kirillplatonov/hotwire-livereload#54]
Doesn't look like reloads happen on error pages (anymore?) — from what it looks like in the code it should be triggering a reload, yeah? I'm not seeing any requests made in the browser after I make a correction of the error in Railsland (and not seeing anything to log or other errors stemming from it).

**Comment by kirillplatonov** [comment]
Tested it on clean Rails 7.1 app and can't reproduce the issue. Reloading on error pages still works. If you still have the issue could you please provide reproduction steps or sample repo where the issue can be checked?

Also, please note that on Rails 7.1 there's an issue with automatic disconnection & reconnection after first reloading. You may encounter it on error page too: https://github.com/kirillplatonov/hotwire-livereload/issues/49

**Comment by holman** [comment]
Looks like it's still present on my app; will dig into it more and see if I can reproduce on a clean app soonish (unfortunately slammed at the moment but will circle back on this!)

**Comment by holman** [comment]
Not sure what's going on here; on my app I'll cause an exception in the view, it'll automatically load the error page, and then when I correct the exception it doesn't reload the error page. Tried a few different combinations and couldn't seem to figure out where the issue stems from. I did try it on a clean app, though, and that doesn't seem to run into the same issues (besides what I suspect is #49), so I'll close this in the meantime.

Will keep an eye out if I can reproduce the issue with my current app and update if there's anything obvious.

**Comment by kirillplatonov** [comment]
Got it, thanks! I will focus on resolving #49 then

**Comment by pjg** [comment]
I'm using [better_errors](https://github.com/BetterErrors/better_errors). Whenever I have a ruby/rails error and error page shows up, after correcting the mistake the page will not reload. I have to manually press Cmd+R to do that. I believe some custom adapter for beter_errors is required for it to work.
