### ISSUE TITLE
Subscription class not found: "Hotwire::Livereload::ReloadChannel"

### ISSUE THREAD

**Issue by crobbo** [kirillplatonov/hotwire-livereload#55]
I installed the gem in a rails project following the readme instructions and it works great. 

However, I'm working on a separate rails project where I do not want to use this gem, therefore I didn't add it to the gemfile or run the install script. Yet I keep getting a warning message in the logs, despite not installing the gem for this project.  

Error:
`Subscription class not found: "Hotwire::Livereload::ReloadChannel"`

Is there a way to prevent this appearing in other rails apps which I am also developing locally? Is there some global setting causing this?

**Comment by varkum** [comment]
Any update on this? Running into the same issue!

**Comment by svs** [comment]
Same issue.

**Comment by dannyk3941** [comment]
Having the same issues as above comments, I've tried disabling `hotwire-livereload` in the project that was using it but creating new rails apps it gives me the same error when I start the app.

**Comment by kirillplatonov** [comment]
Do you have two different apps running locally at the same time? I tried replicating this by generating two Rails apps and installing Hotwire Livereload only to one of them. And I can't reproduce the issue. Even when using Action Cable reloading messages a broadcasted only to app with Hotwire Livereload.

I will need reproduction steps or demo apps to investigate it further.
