### ISSUE TITLE
Restoring Scrollposition after editing JS/CSS

### ISSUE THREAD

**Issue by timteske** [kirillplatonov/hotwire-livereload#56]
Hi, 
i have an issue with the scroll position.
After editing my JS or CSS Code it reloads the page without scrolling to the restored scroll position.
I only changed the listen_paths of the gem because im using postcss to:
` 
config.hotwire_livereload.disable_default_listeners = true 
`
`
config.hotwire_livereload.listen_paths = [Rails.root.join("app/assets/builds")]
`
My console output:
![scroll_position](https://github.com/kirillplatonov/hotwire-livereload/assets/57364309/d6b63a4f-ff5f-407f-9dc5-f5427c0f7332)

**Comment by kirillplatonov** [comment]
Could you please try disabling `data-turbo-track` for CSS like @mikker mentioned in #59?
```diff
+ <%= stylesheet_link_tag "application", "data-turbo-track": Rails.env.production? ? "reload" : "" %>
- <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
```

**Comment by timteske** [comment]
Okay i understand but now it restores the old styling and overwrite it with the new.
That's working for changes of styling but when you removing some, it's not working.
![restoring_styles](https://github.com/kirillplatonov/hotwire-livereload/assets/57364309/fc4604a5-6e60-4949-aaf4-e459758aa885)

**Comment by phallguy** [comment]
Had the same issue myself. Turbo now has a [dynamic](https://turbo.hotwired.dev/handbook/drive#removing-assets-when-they-change) option that worked for me.

```erb
<%= stylesheet_link_tag "application", "data-turbo-track": "dynamic" %>
```

**Comment by timteske** [comment]
Perfekt, that fixed the Problem. Thankyou!

**Comment by jon-sully** [comment]
Switching to `dynamic` solved my gripe! I think that's actually better than the "are you in dev?" current setup

EDIT: my problem being my scroll resetting to the top of the page any time my Tailwind styles rebuilt

**Comment by jon-sully** [comment]
I wish there was a way to do some neat magic with Javascript to prevent reloads, but unfortunately when using import maps they bake in the turbo reload tag:

https://github.com/rails/importmap-rails/blob/cc7142e9996d441aa726eb6e013de29ff990ff60/app/helpers/importmap/importmap_tags_helper.rb#L15
