### ISSUE TITLE
Litestack

### ISSUE THREAD

**Issue by bitsmyth** [kirillplatonov/hotwire-livereload#60]
@kirillplatonov thank you very much for your work on this project. It's a great enhancement for the developer experience. 
Just wanted to drop a note that redis is not required it you use [litestack](https://github.com/oldmoe/litestack) and works out of the box.

**Comment by kirillplatonov** [comment]
Yeah, it seems to work even with default `async` cable adapter starting from Rails 7:
https://github.com/kirillplatonov/hotwire-livereload/pull/68
