### ISSUE TITLE
Support reload over SSE instead of websockets

### ISSUE THREAD

**Issue by ryancbahan** [kirillplatonov/hotwire-livereload#65]
There are a number of Rails projects that don't use ActionCable, but would benefit from this gem. I'm interested in supporting live reload via [ActionController::Live](https://api.rubyonrails.org/v7.1/classes/ActionController/Live.html) and [server-side events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) to establish a connection over http for live reload. 

I'd be happy to take a crack at this if there's interest/alignment.

**Comment by kirillplatonov** [comment]
I'm open to it. It would be great to have more universal alternative to ActionCable!
